# -*- coding: utf-8 -*-
"""qa_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L0gvadsPMauxNg5YSnP2GmnGapuH17HL
"""

!pip install streamlit pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile qa_app.py
# import streamlit as st
# from transformers import pipeline
# 
# st.title("Question Answering with Transformers")
# 
# model_name = "distilbert-base-uncased-distilled-squad"
# qa_pipeline = pipeline("question-answering", model=model_name, tokenizer=model_name)
# 
# context = st.text_area("Enter the context passage:")
# question = st.text_input("Enter your question:")
# 
# if st.button("Get Answer") and context and question:
#     result = qa_pipeline(question=question, context=context)
#     st.markdown(f"**Answer:** {result['answer']}")
#     st.markdown(f"**Confidence Score:** {result['score']:.2f}")

!ngrok config add-authtoken 30VtyANedOoWOFxO2hvkxS5HG4V_DDb3ujdfXjmeyxjaTCXH

import threading
import time
from pyngrok import ngrok

# Kill any previously running Streamlit processes
!pkill streamlit

# Open the tunnel on port 8501
public_url = ngrok.connect(8501)
print(" Streamlit app will be available at:", public_url)

# Function to run streamlit in a thread
def run_streamlit():
    !streamlit run qa_app.py --server.enableCORS false

# Run Streamlit in background thread to avoid blocking
thread = threading.Thread(target=run_streamlit)
thread.start()

# Give it a few seconds to start
time.sleep(5)